from enum import StrEnum

from sqlalchemy import CheckConstraint


def enum_check(column: str, values: type[StrEnum]) -> CheckConstraint:
    """CHECK constraint restricting ``column`` to the members of ``values``.

    Declared explicitly rather than through ``Enum(create_constraint=True)``,
    because the implicit form is invisible to Alembic's metadata comparison: it
    exists in the database but not in the diff, so every autogenerated revision
    emits a ``drop_constraint`` for it. Declaring it here keeps the constraint
    in the metadata Alembic compares against.

    The SQL is derived from the enum, so widening ``VehicleType`` to include
    motorcycles stays a one-line change that autogenerate picks up.
    """
    members = ", ".join(f"'{member.value}'" for member in values)
    # Named for the column; the metadata naming convention expands this to
    # ck_<table>_<column>.
    return CheckConstraint(f"{column} IN ({members})", name=column)
