from enum import StrEnum

from sqlalchemy import CheckConstraint


def enum_check(column: str, values: type[StrEnum]) -> CheckConstraint:
    """CHECK constraint restricting ``column`` to the members of ``values``.

    Explicit rather than ``Enum(create_constraint=True)``: the implicit form is
    invisible to Alembic's comparison, so every autogenerated revision would
    emit a ``drop_constraint`` for it.
    """
    members = ", ".join(f"'{member.value}'" for member in values)
    # The naming convention expands this to ck_<table>_<column>.
    return CheckConstraint(f"{column} IN ({members})", name=column)
