from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import Mapped, mapped_column


class TimestampMixin:
    """Database-side audit timestamps for every persisted entity.

    SQLAlchemy copies a mixin's ``mapped_column`` per mapped subclass, so one
    mixin can safely serve many tables — no per-table Column juggling needed.
    Both values are generated by PostgreSQL, never by Python, so they stay
    correct regardless of which process or clock issued the write.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
