"""create vehicles and rentals

Revision ID: 07bd52dc4710
Revises:
Create Date: 2026-08-25 18:03:58.847660

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "07bd52dc4710"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.Enum("car", name="vehicle_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("registration_number", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "available",
                "in_use",
                "maintenance",
                "retired",
                name="vehicle_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'retired') = (retired_at IS NOT NULL)",
            name=op.f("ck_vehicles_retired_status_matches_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('available', 'in_use', 'maintenance', 'retired')",
            name=op.f("ck_vehicles_status"),
        ),
        sa.CheckConstraint(
            "vehicle_type IN ('car')", name=op.f("ck_vehicles_vehicle_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
    )
    op.create_index(
        op.f("ix_vehicles_registration_number"),
        "vehicles",
        ["registration_number"],
        unique=True,
    )
    op.create_index("ix_vehicles_status", "vehicles", ["status"], unique=False)
    op.create_table(
        "rentals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_at IS NULL OR end_at >= start_at",
            name=op.f("ck_rentals_end_at_after_start_at"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_rentals_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rentals")),
    )
    op.create_index(
        "ix_rentals_vehicle_start_at",
        "rentals",
        ["vehicle_id", sa.literal_column("start_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_rentals_one_active_per_vehicle",
        "rentals",
        ["vehicle_id"],
        unique=True,
        postgresql_where=sa.text("end_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_rentals_one_active_per_vehicle",
        table_name="rentals",
        postgresql_where=sa.text("end_at IS NULL"),
    )
    op.drop_index("ix_rentals_vehicle_start_at", table_name="rentals")
    op.drop_table("rentals")
    op.drop_index("ix_vehicles_status", table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_registration_number"), table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
