"""add customers and rental customer fk

Revision ID: 133f4f0a103b
Revises: 07bd52dc4710
Create Date: 2026-08-26 11:53:58.010482

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "133f4f0a103b"
down_revision: str | None = "07bd52dc4710"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "sex",
            sa.Enum(
                "male",
                "female",
                "unspecified",
                name="sex",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sex IN ('male', 'female', 'unspecified')", name=op.f("ck_customers_sex")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=True)

    # Nullable with no backfill: rentals written before customers existed
    # simply have none, which is the same state a deleted customer leaves
    # behind. SET NULL, not CASCADE — deleting a customer must keep the rental
    # rows and their customer_name snapshot.
    op.add_column("rentals", sa.Column("customer_id", sa.Uuid(), nullable=True))
    op.create_index("ix_rentals_customer_id", "rentals", ["customer_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_rentals_customer_id_customers"),
        "rentals",
        "customers",
        ["customer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_rentals_customer_id_customers"), "rentals", type_="foreignkey"
    )
    op.drop_index("ix_rentals_customer_id", table_name="rentals")
    op.drop_column("rentals", "customer_id")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
